[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.commerce.orders"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.orders"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
