[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "hubspot.crm.commerce.orders"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot","crm", "commerce", "orders"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.orders"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
